### ISSUE TITLE
MSVC Build Failed

### ISSUE THREAD

**Issue by xorz57** [architector1324/vacuum#2]
![image](https://user-images.githubusercontent.com/1548352/47959381-35ef8b80-dfeb-11e8-909d-13d3f65e10e0.png)

**Comment by xorz57** [comment]
Line 10 of `compiler.h` is specific to GNU compilers so it wont work on MSVC.

**Comment by xorz57** [comment]
There are some minor warnings that can be easily fixed.
Line 9 of `lexer.h` should be removed.
Line 5 of `compiler.c` should use %zu instead of %lu.

**Comment by architector1324** [comment]
> Line 10 of `compiler.h` **uses** `__attribute__ ((noreturn))` which is **specific** to GNU compilers so it won't work on MSVC.

Looks like it's a problems of MSVC. We will create a separate branch for the Microsoft platform.

**Comment by architector1324** [comment]
> There are some minor warnings that can be easily fixed.
> Line 9 of `lexer.h` should be **removed**.
> Line 5 of `compiler.c` should **use** `%zu` instead of `%lu`.

Thanks for reply, Line 5 `compiler.c` fixed. Line 9 `lexer.h` will be removed on **MSVC** branch

**Comment by xorz57** [comment]
@architector1324 You can close this Issue if it's fixed.
